This tutorial is for the 6th chapter of *State Estimation for Robtics*.  
Author: Hongpu Liu

In [1]:
%matplotlib inline
from __future__ import print_function, division
import numpy as np
import matplotlib.pyplot as plt

# CHAPTER 6: Primer on Three-Dimensional Geometry

## 6.1 Vectors and Reference Frames

### 6.1.2 Dot Product

In [2]:
# 1 x 4 + 2 x 5 + 3 x 6 = 32
r = np.array([1, 2, 3])
s = np.array([4, 5, 6])

# computer by hand
print('r dot s by hand: ', 1 * 4 + 2 * 5 + 3 * 6)

# use np.inner to cumpute dot product.
# NOTE: r and s MUST be array-like
r_dot_s = np.inner(r, s)
print('r dot s by np.inner: ', r_dot_s)

# use np.dot to cumpute dot product.
# NOTE: r and s MUST be an ndarray, a.k.a. a Matrix
r.reshape((3, 1))
s.reshape((3, 1))
r_dot_s = r.T.dot(s)
print('r dot s by np.dot: ', r_dot_s)

r dot s by hand:  32
r dot s by np.inner:  32
r dot s by np.dot:  32


### 6.1.3 Cross Product

In [3]:
# use np.cross to compute cross product
r = np.array([1, 2, 3])
s = np.array([4, 5, 6])
r_cross_s = np.cross(r, s)
print('r cross s by np.cross:', r_cross_s)

r cross s by np.cross: [-3  6 -3]


In [4]:
# equation (6.2)
def skew_symmetric(vec):
    """
    Computer the skew_symmetric matrix from a vector
    
    Args:
        vec: MUST be an array-like
    """
    
    vec = np.array(vec).reshape(-1,)
    assert vec.shape == (3,), 'vec MUST have three entries'
    skew = np.zeros((3, 3))
    skew[0][1] = -vec[2]
    skew[1][0] = vec[2]
    skew[0][2] = vec[1]
    skew[2][0] = -vec[1]
    skew[1][2] = -vec[0]
    skew[2][1] = vec[0]
    return skew

In [5]:
 # use np.dot and skew_symmetric matrix to compute cross product
r = np.array([1, 2, 3])
s = np.array([4, 5, 6])

r = skew_symmetric(r)
print('skew_symmetric of r:\n', r)

s = s.reshape((3, 1))
r_corss_s = np.dot(r, s)
print('r cross s by np.dot:\n', r_cross_s)

skew_symmetric of r:
 [[ 0. -3.  2.]
 [ 3.  0. -1.]
 [-2.  1.  0.]]
r cross s by np.dot:
 [-3  6 -3]


In [6]:
# transpose of skew_symmetric of r, equal minus skew_symmetric of r
r = np.array([1, 2, 3])
print('transpose of skew_symmetric of r:\n', skew_symmetric(r).T)
print('minus skew_symmetric of r:\n', - skew_symmetric(r))

transpose of skew_symmetric of r:
 [[ 0.  3. -2.]
 [-3.  0.  1.]
 [ 2. -1.  0.]]
minus skew_symmetric of r:
 [[-0.  3. -2.]
 [-3. -0.  1.]
 [ 2. -1. -0.]]


In [7]:
# we'll find that r cross s == - s x r
r = np.array([1, 2, 3])
s = np.array([4, 5, 6])

print('r cross s:\n', np.dot(skew_symmetric(r), s.reshape((3, 1))))
print('s cross r:\n', np.dot(skew_symmetric(s), r.reshape((3, 1))))

r cross s:
 [[-3.]
 [ 6.]
 [-3.]]
s cross r:
 [[ 3.]
 [-6.]
 [ 3.]]


## 6.2 Rotation

### 6.2.1 Rotation Matrics

In [8]:
# define a rotation matrix, along z-axis rotate pi/2
C_21 = np.array([0, -1, 0, 1, 0, 0, 0, 0, 1]).astype('float').reshape((3, 3))
print('C_21:\n', C_21)

# r1 is in Frame1, we'll use C_21 transform to Frame2
r1 = np.array([1, 2, 3]).reshape((3, 1))
print('r1:\n', r1)
r2 = np.dot(C_21, r1)
print('r2 (r1 in Frame2):\n', r2)

# now use inverse of C_21 transform r2 to Frame1
C_12 = np.linalg.inv(C_21)
print('C_12 computed by inverse:\n', C_12)
C_12 = C_21.T
print('C_12 computed by transpose:\n', C_12)

# transform r2 back to Frame1
r1 = np.dot(C_12, r2)
print('r1 transformed from r2 by C_12:\n', r1)

C_21:
 [[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]
r1:
 [[1]
 [2]
 [3]]
r2 (r1 in Frame2):
 [[-2.]
 [ 1.]
 [ 3.]]
C_12 computed by inverse:
 [[ 0.  1.  0.]
 [-1. -0. -0.]
 [ 0.  0.  1.]]
C_12 computed by transpose:
 [[ 0.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
r1 transformed from r2 by C_12:
 [[1.]
 [2.]
 [3.]]


In [9]:
C_21 = np.array([0, -1, 0, 1, 0, 0, 0, 0, 1]).astype('float').reshape((3, 3))
C_32 = np.array([0, -1, 0, 1, 0, 0, 0, 0, 1]).astype('float').reshape((3, 3))
C_31 = np.dot(C_32, C_21)

# r1 is in Frame1
r1 = np.array([1, 2, 3]).reshape((3, 1))

# r3 = C_32 C_21 r1
r3 = np.dot(C_32, np.dot(C_21, r1))
print('r3 = C_32 C_21 r1:\n', r3)

# r3 = C_31 r1
r3 = np.dot(C_31, r1)
print('r3 = C_31 r1:\n', r3)

# You'll find they are equal.

r3 = C_32 C_21 r1:
 [[-1.]
 [-2.]
 [ 3.]]
r3 = C_31 r1:
 [[-1.]
 [-2.]
 [ 3.]]


### 6.2.2 Principal Rotations

In [10]:
def rotation_by_3_axis(theta):
    """
    Computer roatation along z-axis.
    
    Args:
        theta: rotate radian 
    """
    cos_theta = np.cos(theta)
    sin_theta = np.sin(theta)
    C = np.zeros((3, 3))
    C[0][0] = cos_theta
    C[0][1] = sin_theta
    C[1][0] = -sin_theta
    C[1][1] = cos_theta
    C[2][2] = 1.
    return C

rotation_by_3_axis(np.pi / 4) # along z-axis rotate pi / 4

array([[ 0.70710678,  0.70710678,  0.        ],
       [-0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [11]:
def rotation_by_2_axis(theta):
    """
    Computer roatation along z-axis.
    
    Args:
        theta: rotate radian 
    """
    cos_theta = np.cos(theta)
    sin_theta = np.sin(theta)
    C = np.zeros((3, 3))
    C[0][0] = cos_theta
    C[0][2] = -sin_theta
    C[2][0] = sin_theta
    C[2][2] = cos_theta
    C[1][1] = 1.
    return C

rotation_by_2_axis(np.pi / 4) # along z-axis rotate pi / 4

array([[ 0.70710678,  0.        , -0.70710678],
       [ 0.        ,  1.        ,  0.        ],
       [ 0.70710678,  0.        ,  0.70710678]])

In [12]:
def rotation_by_1_axis(theta):
    """
    Computer roatation along z-axis.
    
    Args:
        theta: rotate radian 
    """
    cos_theta = np.cos(theta)
    sin_theta = np.sin(theta)
    C = np.zeros((3, 3))
    C[1][1] = cos_theta
    C[1][2] = sin_theta
    C[2][1] = -sin_theta
    C[2][2] = cos_theta
    C[0][0] = 1.
    return C

rotation_by_1_axis(np.pi / 4) # along z-axis rotate pi / 4

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678,  0.70710678],
       [ 0.        , -0.70710678,  0.70710678]])

### 6.2.3 Alternate Rotation Representations

**Euler Angles**

In [13]:
# equation (6.8)
def euler_angles_3_1_3(theta, gamma, psi):
    """
    Compute Euler rotation matrix in sequence 3-1-3.
    
    Args:
        theta: spin angle, rotate along 3-axis
        gamma: nutation angle, rotate along 1-axis
        psi  : precession angle, rotate along 3-axis
    """
    C_2T = rotation_by_3_axis(theta)
    C_TI = rotation_by_1_axis(gamma)
    C_I1 = rotation_by_3_axis(psi)
    
    C_21 = np.dot(C_2T, np.dot(C_TI, C_I1))
    return C_21

In [14]:
# You'll find when gamma is 0, it have singularities
euler_angles_3_1_3(np.pi / 2, 0, np.pi/ 4)

array([[-0.70710678,  0.70710678,  0.        ],
       [-0.70710678, -0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [15]:
# equation (6.9)
def euler_angles_1_2_3(theta3, theta2, theta1):
    """
    Compute Euler rotation matrix in sequence 1-2-3.
    
    Args:
        theta3: roll, rotate along 3-axis
        theta2: pitch, rotate along 2-axis
        theta1: yaw, rotate along 1-axis
    """
    C_3 = rotation_by_3_axis(theta3)
    C_2 = rotation_by_2_axis(theta2)
    C_1 = rotation_by_1_axis(theta1)
    
    C = np.dot(C_3, np.dot(C_2, C_1))
    return C

In [16]:
# You'll find when theta2 is PI/2, it have singularities
C = euler_angles_1_2_3(np.pi / 3, np.pi / 2, np.pi / 4)
C[np.abs(C) < 1e-10] = 0
print(C)

[[ 0.          0.96592583  0.25881905]
 [ 0.         -0.25881905  0.96592583]
 [ 1.          0.          0.        ]]


**Infinitesimal Rotation**

In [17]:
def euler_angles_1_2_3_approximation(theta3, theta2, theta1):
    """
    Compute approximation rotation matrix, when all thetas are infinitesimal.
    
    Args:
        theta3: roll, rotate along 3-axis
        theta2: pitch, rotate along 2-axis
        theta1: yaw, rotate along 1-axis
    """
    theta = [theta1, theta2, theta3]
    return np.identity(3) - skew_symmetric(theta)

In [18]:
theta = {'theta3': 1e-7, 'theta2': 1e-5, 'theta1': 1e-6}
C_approximation = euler_angles_1_2_3_approximation(**theta)
print(C_approximation)

[[ 1.e+00  1.e-07 -1.e-05]
 [-1.e-07  1.e+00  1.e-06]
 [ 1.e-05 -1.e-06  1.e+00]]


In [19]:
C_euler = euler_angles_1_2_3(**theta)
print(C_euler)

[[ 1.0000000e+00  1.0001000e-07 -9.9999999e-06]
 [-1.0000000e-07  1.0000000e+00  1.0000010e-06]
 [ 1.0000000e-05 -1.0000000e-06  1.0000000e+00]]


In [20]:
print('C_approximation - C_euler:')
print( C_approximation - C_euler)
print('\nFrobenius Norm of the different:')
print(np.linalg.norm(C_approximation - C_euler))

C_approximation - C_euler:
[[ 5.00050001e-11 -9.99999995e-12 -1.00171717e-13]
 [-5.00016784e-18  5.05040454e-13 -9.99999828e-13]
 [ 1.66667285e-16 -5.01665851e-17  5.05000486e-11]]

Frobenius Norm of the different:
7.177757341466728e-11


**Euler Parameters**

In [21]:
# Equation (6.15)
def euler_parameters_2_rotation_matrix(euler_parameters):
    """
    Compute rotation matrix from euler parameters.
    
    Args:
        euler_parameters: an array-like with 4 entries.
    """
    
    euler_parameters = np.array(euler_parameters)
    assert euler_parameters.shape == (4, ), "Euler parameters MUST have four entries."
    
    # the euler parameters MUST be a unit vector
    euler_parameters = euler_parameters / np.linalg.norm(euler_parameters)
    
    # divide the vector into two part:
    # epsilon = rotation axis * sin(rotation angle / 2)
    epsilon = euler_parameters[:3].reshape((3, 1)) 
    # eta = cos( rotation angle / 2)
    eta = euler_parameters[3]
    
    C  = (eta ** 2 - np.dot(epsilon.T, epsilon)[0][0]) * np.identity(3)
    C += 2 * np.dot(epsilon, epsilon.T)
    C += - 2 * eta * skew_symmetric(epsilon)
    
    return C
    
C = euler_parameters_2_rotation_matrix([1, 2, 3, 4])
print(C)
print('result of C dot C.T almost an identity:')
print(np.dot(C, C.T))

[[ 0.13333333  0.93333333 -0.33333333]
 [-0.66666667  0.33333333  0.66666667]
 [ 0.73333333  0.13333333  0.66666667]]
result of C dot C.T almost an identity:
[[ 1.00000000e+00  2.77555756e-17  8.32667268e-17]
 [ 2.77555756e-17  1.00000000e+00 -5.55111512e-17]
 [ 8.32667268e-17 -5.55111512e-17  1.00000000e+00]]


**Quaternions**

In [22]:
# computer unit quaternion
def quaternion_unit(q):
    """
    Computer a unit quaternion.
    
    Args:
        q: a quaternion, which has 4 entries. First three are epsilon, last entry is eta.
    """
    q = np.array(q).reshape((-1,))
    assert q.shape == (4,), 'Quaternion MUST have four entries.'
    
    q = q / np.linalg.norm(q)
    
    q = q.reshape((4, 1))
    
    return q

In [23]:
# Equation (6.17) left-hand compound operator
def quaternion_left_hand_compound(q):
    """
    Quaternion left-hand compound operator.
    
    Args:
        q: a quaternion, which has 4 entries. First three are epsilon, last entry is eta.
    """
    q = np.array(q).reshape((-1,))
    assert q.shape == (4,), 'Quaternion MUST have four entries.'
    
#     q = quaternion_unit(q)
    
    epsilon = q[:3].reshape(3, 1)
    eta = q[3]
    
    result = np.zeros((4, 4))
    result[:3, :3] = eta * np.identity(3) - skew_symmetric(epsilon)
    result[:3, 3]  = epsilon.T
    result[3, :3]  = - epsilon.T
    result[3, 3]   = eta
    
    return result
    
quaternion_left_hand_compound([3, 2, 1, 2])

array([[ 2.,  1., -2.,  3.],
       [-1.,  2.,  3.,  2.],
       [ 2., -3.,  2.,  1.],
       [-3., -2., -1.,  2.]])

In [24]:
# Equation (6.17) right-hand compound operator
def quaternion_right_hand_compound(q):
    """
    Quaternion right-hand compound operator.
    
    Args:
        q: a quaternion, which has 4 entries. First three are epsilon, last entry is eta.
    """
    q = np.array(q).reshape((-1,))
    assert q.shape == (4,), 'Quaternion MUST have four entries.'
    
#     q = quaternion_unit(q)
    
    epsilon = q[:3].reshape(3, 1)
    eta = q[3]
    
    result = np.zeros((4, 4))
    result[:3, :3] = eta * np.identity(3) + skew_symmetric(epsilon)
    result[:3, 3]  = epsilon.T
    result[3, :3]  = - epsilon.T
    result[3, 3]   = eta
    
    return result
    
quaternion_right_hand_compound([3, 2, 1, 2])

array([[ 2., -1.,  2.,  3.],
       [ 1.,  2., -3.,  2.],
       [-2.,  3.,  2.,  1.],
       [-3., -2., -1.,  2.]])

In [25]:
# Equation (6.18), quternion inverse operator
def quaternion_inverse(q):
    """
    Quaternion inverse operator.
    
    Args:
        q: a quaternion, which has 4 entries. First three are epsilon, last entry is eta.
    """
    q = np.array(q).reshape((-1,))
    assert q.shape == (4,), 'Quaternion MUST have four entries.'
    
    epsilon = q[:3].reshape(3, 1)
    eta = q[3]
    
    result = np.zeros((4, 1))
    result[:3, 0]  = - epsilon.T
    result[ 3, 0]  = eta
    
    return result

quaternion_inverse([3, 2, 1, 2])

array([[-3.],
       [-2.],
       [-1.],
       [ 2.]])

In [26]:
# validate equation (6.19)
u = np.array([3, 2, 1, 3]).reshape((4, 1))
u = quaternion_unit(u)
v = np.array([4, 6, 3, 2]).reshape((4, 1))
v = quaternion_unit(v)

print('left-compound(u) dot v:')
print(np.dot(quaternion_left_hand_compound(u), quaternion_unit(v)))
print('right-compound(v) dot u:')
print(np.dot(quaternion_right_hand_compound(v), quaternion_unit(u)))

left-compound(u) dot v:
[[ 0.46553454]
 [ 0.69830181]
 [ 0.02586303]
 [-0.54312363]]
right-compound(v) dot u:
[[ 0.46553454]
 [ 0.69830181]
 [ 0.02586303]
 [-0.54312363]]


In [27]:
# validate equation (6.20) row 1 col 1
u = np.array([3, 2, 1, 3]).reshape((4, 1))
u = quaternion_unit(u)
v = np.array([4, 6, 3, 2]).reshape((4, 1))
v = quaternion_unit(v)

print('transopose of left-compound(u):')
print(quaternion_left_hand_compound(u).T)
print('inverse of left-compound(u):')
print(np.linalg.inv(quaternion_left_hand_compound(u)))
print('left-compound(quaternion_inverse of u):')
print(quaternion_left_hand_compound(quaternion_inverse(u)))

transopose of left-compound(u):
[[ 0.62554324 -0.20851441  0.41702883 -0.62554324]
 [ 0.20851441  0.62554324 -0.62554324 -0.41702883]
 [-0.41702883  0.62554324  0.62554324 -0.20851441]
 [ 0.62554324  0.41702883  0.20851441  0.62554324]]
inverse of left-compound(u):
[[ 0.62554324 -0.20851441  0.41702883 -0.62554324]
 [ 0.20851441  0.62554324 -0.62554324 -0.41702883]
 [-0.41702883  0.62554324  0.62554324 -0.20851441]
 [ 0.62554324  0.41702883  0.20851441  0.62554324]]
left-compound(quaternion_inverse of u):
[[ 0.62554324 -0.20851441  0.41702883 -0.62554324]
 [ 0.20851441  0.62554324 -0.62554324 -0.41702883]
 [-0.41702883  0.62554324  0.62554324 -0.20851441]
 [ 0.62554324  0.41702883  0.20851441  0.62554324]]


In [28]:
# validate equation (6.20) row 1 col 2
u = np.array([3, 2, 1, 3]).reshape((4, 1))
u = quaternion_unit(u)
v = np.array([4, 6, 3, 2]).reshape((4, 1))
v = quaternion_unit(v)

print('transopose of right-compound(u):')
print(quaternion_right_hand_compound(u).T)
print('inverse of right-compound(u):')
print(np.linalg.inv(quaternion_right_hand_compound(u)))
print('right-compound(quaternion_inverse of u):')
print(quaternion_right_hand_compound(quaternion_inverse(u)))

transopose of right-compound(u):
[[ 0.62554324  0.20851441 -0.41702883 -0.62554324]
 [-0.20851441  0.62554324  0.62554324 -0.41702883]
 [ 0.41702883 -0.62554324  0.62554324 -0.20851441]
 [ 0.62554324  0.41702883  0.20851441  0.62554324]]
inverse of right-compound(u):
[[ 0.62554324  0.20851441 -0.41702883 -0.62554324]
 [-0.20851441  0.62554324  0.62554324 -0.41702883]
 [ 0.41702883 -0.62554324  0.62554324 -0.20851441]
 [ 0.62554324  0.41702883  0.20851441  0.62554324]]
right-compound(quaternion_inverse of u):
[[ 0.62554324  0.20851441 -0.41702883 -0.62554324]
 [-0.20851441  0.62554324  0.62554324 -0.41702883]
 [ 0.41702883 -0.62554324  0.62554324 -0.20851441]
 [ 0.62554324  0.41702883  0.20851441  0.62554324]]


In [29]:
# validate equation (6.20) row 2 col 1
u = np.array([3, 2, 1, 3]).reshape((4, 1))
u = quaternion_unit(u)
v = np.array([4, 6, 3, 2]).reshape((4, 1))
v = quaternion_unit(v)

print('inverse of (left-compound(u) dot v):')
print(quaternion_inverse(np.dot(quaternion_left_hand_compound(u), v)))
print('left-compound(inverse of u) dot (inverse of v)')
print(np.dot(
        quaternion_left_hand_compound(quaternion_inverse(v)),
        quaternion_inverse(u)))

inverse of (left-compound(u) dot v):
[[-0.46553454]
 [-0.69830181]
 [-0.02586303]
 [-0.54312363]]
left-compound(inverse of u) dot (inverse of v)
[[-0.46553454]
 [-0.69830181]
 [-0.02586303]
 [-0.54312363]]


In [30]:
# validate equation (6.20) row 2 col 2
u = np.array([3, 2, 1, 3]).reshape((4, 1))
# u = quaternion_unit(u)
v = np.array([4, 6, 3, 2]).reshape((4, 1))
# v = quaternion_unit(v)

print('inverse of (right-compound(u) dot v):')
print(quaternion_inverse(np.dot(quaternion_right_hand_compound(u), v)))
print('right-compound(inverse of u) dot (inverse of v)')
print(np.dot(
        quaternion_right_hand_compound(quaternion_inverse(v)),
        quaternion_inverse(u)))

inverse of (right-compound(u) dot v):
[[-18.]
 [-17.]
 [-21.]
 [-21.]]
right-compound(inverse of u) dot (inverse of v)
[[-18.]
 [-17.]
 [-21.]
 [-21.]]


In [31]:
# validate equation (6.20) row 3 col 1
u = np.array([3, 2, 1, 3]).reshape((4, 1))
v = np.array([4, 6, 3, 2]).reshape((4, 1))
w = np.array([4, 6, 3, 2]).reshape((4, 1))
u_left = quaternion_left_hand_compound(u)
v_left = quaternion_left_hand_compound(v)

print('First term:')
result = np.dot(u_left, v)
result = quaternion_left_hand_compound(result)
result = np.dot(result, w)
print(result)

print('Second term:')
result = np.dot(v_left, w)
result = np.dot(u_left, result)
print(result)

print('Third term:')
result = np.dot(u_left, v_left)
result = np.dot(result, w)
print(result)

First term:
[[-123.]
 [ -22.]
 [ -61.]
 [-279.]]
Second term:
[[-123.]
 [ -22.]
 [ -61.]
 [-279.]]
Third term:
[[-123.]
 [ -22.]
 [ -61.]
 [-279.]]


In [32]:
# validate equation (6.20) row 3 col 2
u = np.array([3, 2, 1, 3]).reshape((4, 1))
v = np.array([4, 6, 3, 2]).reshape((4, 1))
w = np.array([4, 6, 3, 2]).reshape((4, 1))
u_right = quaternion_right_hand_compound(u)
v_right = quaternion_right_hand_compound(v)

print('First term:')
result = np.dot(u_right, v)
result = quaternion_right_hand_compound(result)
result = np.dot(result, w)
print(result)

print('Second term:')
result = np.dot(v_right, w)
result = np.dot(u_right, result)
print(result)

print('Third term:')
result = np.dot(u_right, v_right)
result = np.dot(result, w)
print(result)

First term:
[[-123.]
 [ -62.]
 [  19.]
 [-279.]]
Second term:
[[-123.]
 [ -62.]
 [  19.]
 [-279.]]
Third term:
[[-123.]
 [ -62.]
 [  19.]
 [-279.]]


In [33]:
# validate equation (6.20) row 4 col 1
u = np.array([3, 2, 1, 3]).reshape((4, 1))
u = u / np.linalg.norm(u)
v = np.array([4, 6, 3, 2]).reshape((4, 1))
v = v / np.linalg.norm(v)
alpha = 2.3
beta = 4.6

print('First term:')
result = alpha * quaternion_left_hand_compound(u) + \
        beta * quaternion_left_hand_compound(v)
print(result)

print('Second term:')
result = quaternion_left_hand_compound(alpha * u + beta * v)
print(result)

First term:
[[ 2.57986902  2.19126249 -4.38252498  3.72098857]
 [-2.19126249  2.57986902  3.72098857  4.38252498]
 [ 4.38252498 -3.72098857  2.57986902  2.19126249]
 [-3.72098857 -4.38252498 -2.19126249  2.57986902]]
Second term:
[[ 2.57986902  2.19126249 -4.38252498  3.72098857]
 [-2.19126249  2.57986902  3.72098857  4.38252498]
 [ 4.38252498 -3.72098857  2.57986902  2.19126249]
 [-3.72098857 -4.38252498 -2.19126249  2.57986902]]


In [34]:
# validate equation (6.20) row 4 col 2
u = np.array([3, 2, 1, 3]).reshape((4, 1))
v = np.array([4, 6, 3, 2]).reshape((4, 1))
alpha = 2.3
beta = 4.6

print('First term:')
result = alpha * quaternion_right_hand_compound(u) + \
        beta * quaternion_right_hand_compound(v)
print(result)

print('Second term:')
result = quaternion_right_hand_compound(alpha * u + beta * v)
print(result)

First term:
[[ 16.1 -16.1  32.2  25.3]
 [ 16.1  16.1 -25.3  32.2]
 [-32.2  25.3  16.1  16.1]
 [-25.3 -32.2 -16.1  16.1]]
Second term:
[[ 16.1 -16.1  32.2  25.3]
 [ 16.1  16.1 -25.3  32.2]
 [-32.2  25.3  16.1  16.1]
 [-25.3 -32.2 -16.1  16.1]]


In [35]:
# validate equation (6.21)
u = np.array([3, 2, 1, 3]).reshape((4, 1))
v = np.array([4, 6, 3, 2]).reshape((4, 1))
u_left = quaternion_left_hand_compound(u)
v_right = quaternion_right_hand_compound(v)

print('First term:')
print(np.dot(u_left, v_right))

print('Second term:')
print(np.dot(v_right, u_left))

First term:
[[  9. -33.   1.  18.]
 [-19.   9. -18.  27.]
 [-27.  -6.  27.   1.]
 [-18. -17. -21. -21.]]
Second term:
[[  9. -33.   1.  18.]
 [-19.   9. -18.  27.]
 [-27.  -6.  27.   1.]
 [-18. -17. -21. -21.]]


In [36]:
# Equation (6.22)
q = [0, 0, 0, 1]

print('left-compound of q:')
print(quaternion_left_hand_compound(q))

print('right-compound of q:')
print(quaternion_right_hand_compound(q))

left-compound of q:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
right-compound of q:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


*In rotation, q **MUST** be a unit-length vector.*

In [37]:
# Equation (6.24), v is a point in Homogeneous form
v = np.array([3, 4, 2, 1]).reshape((4, 1))
print("v:")
print(v)

q = np.array([1, 2, 3, 4])
q = q / np.linalg.norm(q)

# Equation (6.25)
print('First term:')
q_left = quaternion_left_hand_compound(q)
v_left = quaternion_left_hand_compound(v)
q_inv = quaternion_inverse(q)
result = np.dot(np.dot(q_left, v_left), q_inv)
print(result)

print('Second term:')
q_left = quaternion_left_hand_compound(q)
q_inv_right = quaternion_right_hand_compound(quaternion_inverse(q))
result = np.dot(np.dot(q_left, q_inv_right), v)
print(result)

v:
[[3]
 [4]
 [2]
 [1]]
First term:
[[3.46666667]
 [0.66666667]
 [4.06666667]
 [1.        ]]
Second term:
[[3.46666667]
 [0.66666667]
 [4.06666667]
 [1.        ]]


In [38]:
# Equation (6.26)
q_left = quaternion_left_hand_compound(q)
q_inv_right = quaternion_right_hand_compound(quaternion_inverse(q))
q_right_t = quaternion_right_hand_compound(q).T

print('First term:')
result = np.dot(q_left, q_inv_right)
print(result)

print('Second term:')
result = np.dot(q_inv_right, q_left)
print(result)

print('Third term:')
result = np.dot(q_right_t, q_left)
print(result)

print('Fourth term')
result = euler_parameters_2_rotation_matrix(q)
print(result)

First term:
[[ 1.33333333e-01  9.33333333e-01 -3.33333333e-01  2.77555756e-17]
 [-6.66666667e-01  3.33333333e-01  6.66666667e-01  0.00000000e+00]
 [ 7.33333333e-01  1.33333333e-01  6.66666667e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Second term:
[[ 1.33333333e-01  9.33333333e-01 -3.33333333e-01 -2.77555756e-17]
 [-6.66666667e-01  3.33333333e-01  6.66666667e-01  0.00000000e+00]
 [ 7.33333333e-01  1.33333333e-01  6.66666667e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Third term:
[[ 1.33333333e-01  9.33333333e-01 -3.33333333e-01 -2.77555756e-17]
 [-6.66666667e-01  3.33333333e-01  6.66666667e-01  0.00000000e+00]
 [ 7.33333333e-01  1.33333333e-01  6.66666667e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Fourth term
[[ 0.13333333  0.93333333 -0.33333333]
 [-0.66666667  0.33333333  0.66666667]
 [ 0.73333333  0.13333333  0.66666667]]


In [77]:
# define the result
def quaternion_2_rotate_matrix(q):
    """
    Compute rotation matrix from quaternion.
    
    Args:
        q: an array-like with 4 entries.
    """
    
    euler_parameters = np.array(q)
    assert euler_parameters.shape == (4, ), "Euler parameters MUST have four entries."
    
    # the euler parameters MUST be a unit vector
    q = q / np.linalg.norm(q)
    
    q_left = quaternion_left_hand_compound(q)
    q_inv_right = quaternion_right_hand_compound(quaternion_inverse(q))
    
    C = np.dot(q_left, q_inv_right)
    
    C = C[:3, :3]
    
    return C

q = np.array([0, 0, 1, 3])
print(quaternion_2_rotate_matrix(q))

print('-' * 40)

q = np.array([0, 0, -1, 3])
print(quaternion_2_rotate_matrix(q))

# NOTE: the two rotate matrix, the transpose of the first matrix equal the second matrix.

[[ 0.8  0.6  0. ]
 [-0.6  0.8  0. ]
 [ 0.   0.   1. ]]
----------------------------------------
[[ 0.8 -0.6  0. ]
 [ 0.6  0.8  0. ]
 [ 0.   0.   1. ]]


**Gibbs Vector**

In [51]:
# Equation (6.27)
a = np.array([1, 2, 3])
a = a / np.linalg.norm(a)
phi = np.pi / 4

g = a * np.tan(phi / 2)
print(g)

[0.11070323 0.22140646 0.33210969]


In [68]:
def gibbs_2_rotate_matrix(g):
    """
    Computer rotate matrix from gibbs vector.
    
    Args:
        g: an array-like with 3 entries. 
    """
    g = np.array(g).reshape((-1,))
    assert g.shape == (3,), 'gibbs vector MUST have 3 entries.'
    
    g_skew = skew_symmetric(g)
    g = g.reshape((3, 1))
    g_inner = np.dot(g.T, g)[0][0]
    factor = 1 / (1 + g_inner)
    
    C  = (1 - g_inner) * np.identity(3)
    C += 2 * np.dot(g, g.T)
    C -= 2 * g_skew
    C  = factor * C
    
    return C
    
gibbs_2_rotate_matrix(g)

array([[ 0.72802773,  0.6087886 , -0.31520164],
       [-0.52510482,  0.79079056,  0.3145079 ],
       [ 0.44072731, -0.06345657,  0.89539528]])

In [70]:
# along z-axis rotate pi/4
a = np.array([0, 0, 1])
a = a / np.linalg.norm(a)
phi = np.pi / 4

g = a * np.tan(phi / 2)

gibbs_2_rotate_matrix(g)

array([[ 0.70710678,  0.70710678,  0.        ],
       [-0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [74]:
# along y-axis rotate pi/4
a = np.array([0, 1, 0])
a = a / np.linalg.norm(a)
phi = np.pi / 4

g = a * np.tan(phi / 2)

gibbs_2_rotate_matrix(g)

array([[ 0.70710678,  0.        , -0.70710678],
       [ 0.        ,  1.        ,  0.        ],
       [ 0.70710678,  0.        ,  0.70710678]])

In [75]:
# along x-axis rotate pi/4
a = np.array([1, 0, 0])
a = a / np.linalg.norm(a)
phi = np.pi / 4

g = a * np.tan(phi / 2)

gibbs_2_rotate_matrix(g)

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678,  0.70710678],
       [ 0.        , -0.70710678,  0.70710678]])