This tutorial is for the 6th chapter of *State Estimation for Robtics*.  
Author: Hongpu Liu

In [1]:
%matplotlib inline
from __future__ import print_function, division
import numpy as np
import matplotlib.pyplot as plt

# CHAPTER 6: Primer on Three-Dimensional Geometry

## 6.1 Vectors and Reference Frames

### 6.1.2 Dot Product

In [2]:
# 1 x 4 + 2 x 5 + 3 x 6 = 32
r = np.array([1, 2, 3])
s = np.array([4, 5, 6])

# computer by hand
print('r dot s by hand: ', 1 * 4 + 2 * 5 + 3 * 6)

# use np.inner to cumpute dot product.
# NOTE: r and s MUST be array-like
r_dot_s = np.inner(r, s)
print('r dot s by np.inner: ', r_dot_s)

# use np.dot to cumpute dot product.
# NOTE: r and s MUST be an ndarray, a.k.a. a Matrix
r.reshape((3, 1))
s.reshape((3, 1))
r_dot_s = r.T.dot(s)
print('r dot s by np.dot: ', r_dot_s)

r dot s by hand:  32
r dot s by np.inner:  32
r dot s by np.dot:  32


### 6.1.3 Cross Product

In [3]:
# use np.cross to compute cross product
r = np.array([1, 2, 3])
s = np.array([4, 5, 6])
r_cross_s = np.cross(r, s)
print('r cross s by np.cross:', r_cross_s)

r cross s by np.cross: [-3  6 -3]


In [4]:
# equation (6.2)
def skew_symmetric(vec):
    """
    Computer the skew_symmetric matrix from a vector
    
    Args:
        vec: MUST be an array-like
    """
    
    vec = np.array(vec)
    assert vec.shape == (3,), 'vec MUST have three entries'
    skew = np.zeros((3, 3))
    skew[0][1] = -vec[2]
    skew[1][0] = vec[2]
    skew[0][2] = vec[1]
    skew[2][0] = -vec[1]
    skew[1][2] = -vec[0]
    skew[2][1] = vec[0]
    return skew

In [5]:
 # use np.dot and skew_symmetric matrix to compute cross product
r = np.array([1, 2, 3])
s = np.array([4, 5, 6])

r = skew_symmetric(r)
print('skew_symmetric of r:\n', r)

s = s.reshape((3, 1))
r_corss_s = np.dot(r, s)
print('r cross s by np.dot:\n', r_cross_s)

skew_symmetric of r:
 [[ 0. -3.  2.]
 [ 3.  0. -1.]
 [-2.  1.  0.]]
r cross s by np.dot:
 [-3  6 -3]


In [6]:
# transpose of skew_symmetric of r, equal minus skew_symmetric of r
r = np.array([1, 2, 3])
print('transpose of skew_symmetric of r:\n', skew_symmetric(r).T)
print('minus skew_symmetric of r:\n', - skew_symmetric(r))

transpose of skew_symmetric of r:
 [[ 0.  3. -2.]
 [-3.  0.  1.]
 [ 2. -1.  0.]]
minus skew_symmetric of r:
 [[-0.  3. -2.]
 [-3. -0.  1.]
 [ 2. -1. -0.]]


In [7]:
# we'll find that r cross s == - s x r
r = np.array([1, 2, 3])
s = np.array([4, 5, 6])

print('r cross s:\n', np.dot(skew_symmetric(r), s.reshape((3, 1))))
print('s cross r:\n', np.dot(skew_symmetric(s), r.reshape((3, 1))))

r cross s:
 [[-3.]
 [ 6.]
 [-3.]]
s cross r:
 [[ 3.]
 [-6.]
 [ 3.]]


## 6.2 Rotation

### 6.2.1 Rotation Matrics

In [8]:
# define a rotation matrix, along z-axis rotate pi/2
C_21 = np.array([0, -1, 0, 1, 0, 0, 0, 0, 1]).astype('float').reshape((3, 3))
print('C_21:\n', C_21)

# r1 is in Frame1, we'll use C_21 transform to Frame2
r1 = np.array([1, 2, 3]).reshape((3, 1))
print('r1:\n', r1)
r2 = np.dot(C_21, r1)
print('r2 (r1 in Frame2):\n', r2)

# now use inverse of C_21 transform r2 to Frame1
C_12 = np.linalg.inv(C_21)
print('C_12 computed by inverse:\n', C_12)
C_12 = C_21.T
print('C_12 computed by transpose:\n', C_12)

# transform r2 back to Frame1
r1 = np.dot(C_12, r2)
print('r1 transformed from r2 by C_12:\n', r1)

C_21:
 [[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]
r1:
 [[1]
 [2]
 [3]]
r2 (r1 in Frame2):
 [[-2.]
 [ 1.]
 [ 3.]]
C_12 computed by inverse:
 [[ 0.  1.  0.]
 [-1. -0. -0.]
 [ 0.  0.  1.]]
C_12 computed by transpose:
 [[ 0.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
r1 transformed from r2 by C_12:
 [[1.]
 [2.]
 [3.]]


In [9]:
C_21 = np.array([0, -1, 0, 1, 0, 0, 0, 0, 1]).astype('float').reshape((3, 3))
C_32 = np.array([0, -1, 0, 1, 0, 0, 0, 0, 1]).astype('float').reshape((3, 3))
C_31 = np.dot(C_32, C_21)

# r1 is in Frame1
r1 = np.array([1, 2, 3]).reshape((3, 1))

# r3 = C_32 C_21 r1
r3 = np.dot(C_32, np.dot(C_21, r1))
print('r3 = C_32 C_21 r1:\n', r3)

# r3 = C_31 r1
r3 = np.dot(C_31, r1)
print('r3 = C_31 r1:\n', r3)

# You'll find they are equal.

r3 = C_32 C_21 r1:
 [[-1.]
 [-2.]
 [ 3.]]
r3 = C_31 r1:
 [[-1.]
 [-2.]
 [ 3.]]


### 6.2.2 Principal Rotations

In [10]:
def rotation_by_3_axis(theta):
    """
    Computer roatation along z-axis.
    
    Args:
        theta: rotate radian 
    """
    cos_theta = np.cos(theta)
    sin_theta = np.sin(theta)
    C = np.zeros((3, 3))
    C[0][0] = cos_theta
    C[0][1] = sin_theta
    C[1][0] = -sin_theta
    C[1][1] = cos_theta
    C[2][2] = 1.
    return C

rotation_by_3_axis(np.pi / 4) # along z-axis rotate pi / 4

array([[ 0.70710678,  0.70710678,  0.        ],
       [-0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [11]:
def rotation_by_2_axis(theta):
    """
    Computer roatation along z-axis.
    
    Args:
        theta: rotate radian 
    """
    cos_theta = np.cos(theta)
    sin_theta = np.sin(theta)
    C = np.zeros((3, 3))
    C[0][0] = cos_theta
    C[0][2] = -sin_theta
    C[2][0] = sin_theta
    C[2][2] = cos_theta
    C[1][1] = 1.
    return C

rotation_by_2_axis(np.pi / 4) # along z-axis rotate pi / 4

array([[ 0.70710678,  0.        , -0.70710678],
       [ 0.        ,  1.        ,  0.        ],
       [ 0.70710678,  0.        ,  0.70710678]])

In [12]:
def rotation_by_1_axis(theta):
    """
    Computer roatation along z-axis.
    
    Args:
        theta: rotate radian 
    """
    cos_theta = np.cos(theta)
    sin_theta = np.sin(theta)
    C = np.zeros((3, 3))
    C[1][1] = cos_theta
    C[1][2] = sin_theta
    C[2][1] = -sin_theta
    C[2][2] = cos_theta
    C[0][0] = 1.
    return C

rotation_by_1_axis(np.pi / 4) # along z-axis rotate pi / 4

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678,  0.70710678],
       [ 0.        , -0.70710678,  0.70710678]])

### 6.2.3 Alternate Rotation Representations

**Euler Angles**

In [13]:
# equation (6.8)
def euler_angles_3_1_3(theta, gamma, psi):
    """
    Compute Euler rotation matrix in sequence 3-1-3.
    
    Args:
        theta: spin angle, rotate along 3-axis
        gamma: nutation angle, rotate along 1-axis
        psi  : precession angle, rotate along 3-axis
    """
    C_2T = rotation_by_3_axis(theta)
    C_TI = rotation_by_1_axis(gamma)
    C_I1 = rotation_by_3_axis(psi)
    
    C_21 = np.dot(C_2T, np.dot(C_TI, C_I1))
    return C_21

In [14]:
# You'll find when gamma is 0, it have singularities
euler_angles_3_1_3(np.pi / 2, 0, np.pi/ 4)

array([[-0.70710678,  0.70710678,  0.        ],
       [-0.70710678, -0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [15]:
# equation (6.9)
def euler_angles_1_2_3(theta3, theta2, theta1):
    """
    Compute Euler rotation matrix in sequence 1-2-3.
    
    Args:
        theta3: roll, rotate along 3-axis
        theta2: pitch, rotate along 2-axis
        theta1: yaw, rotate along 1-axis
    """
    C_3 = rotation_by_3_axis(theta3)
    C_2 = rotation_by_2_axis(theta2)
    C_1 = rotation_by_1_axis(theta1)
    
    C = np.dot(C_3, np.dot(C_2, C_1))
    return C

In [16]:
# You'll find when theta2 is PI/2, it have singularities
C = euler_angles_1_2_3(np.pi / 3, np.pi / 2, np.pi / 4)
C[np.abs(C) < 1e-10] = 0
print(C)

[[ 0.          0.96592583  0.25881905]
 [ 0.         -0.25881905  0.96592583]
 [ 1.          0.          0.        ]]


**Infinitesimal Rotation**

In [17]:
def euler_angles_1_2_3_approximation(theta3, theta2, theta1):
    """
    Compute approximation rotation matrix, when all thetas are infinitesimal.
    
    Args:
        theta3: roll, rotate along 3-axis
        theta2: pitch, rotate along 2-axis
        theta1: yaw, rotate along 1-axis
    """
    theta = [theta1, theta2, theta3]
    return np.identity(3) - skew_symmetric(theta)

In [18]:
theta = {'theta3': 1e-7, 'theta2': 1e-5, 'theta1': 1e-6}
C_approximation = euler_angles_1_2_3_approximation(**theta)
print(C_approximation)

[[ 1.e+00  1.e-07 -1.e-05]
 [-1.e-07  1.e+00  1.e-06]
 [ 1.e-05 -1.e-06  1.e+00]]


In [19]:
C_euler = euler_angles_1_2_3(**theta)
print(C_euler)

[[ 1.0000000e+00  1.0001000e-07 -9.9999999e-06]
 [-1.0000000e-07  1.0000000e+00  1.0000010e-06]
 [ 1.0000000e-05 -1.0000000e-06  1.0000000e+00]]


In [21]:
print('C_approximation - C_euler:')
print( C_approximation - C_euler)
print('\nFrobenius Norm of the different:')
print(np.linalg.norm(C_approximation - C_euler))

C_approximation - C_euler:
[[ 5.00050001e-11 -9.99999995e-12 -1.00171717e-13]
 [-5.00016784e-18  5.05040454e-13 -9.99999828e-13]
 [ 1.66667285e-16 -5.01665851e-17  5.05000486e-11]]

Frobenius Norm of the different:
7.177757341466728e-11


**Euler Parameters**